name: object_detection_env
channels:
  - defaults
dependencies:
  - python=3.12
  - pip
  - pip:
      - mlflow
      - yolov8
      - ultralytics
      - opencv-python
      - opencv-python-headless
